# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2026 Simon Glass <sjg@chromium.org>

obj-$(CONFIG_DEBUG_DEV) += debug-uclass.o
obj-$(CONFIG_DEBUG_EM100) += em100.o
obj-$(CONFIG_DEBUG_SANDBOX) += debug_sandbox.o
