# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2026 Simon Glass <sjg@chromium.org>

obj-y += cpu.o
obj-y += e820.o
obj-y += mpio.o
obj-y += pci.o
obj-$(CONFIG_CMDLINE) += fch.o
obj-$(CONFIG_CMDLINE) += smn.o
obj-$(CONFIG_CMDLINE) += mca.o
