# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2026 Simon Glass <sjg@chromium.org>

obj-$(CONFIG_GENERATE_ACPI_TABLE) += acpi.o
obj-$(CONFIG_GENERATE_ACPI_TABLE) += ivrs.o
obj-y += ap_start.o
obj-y += apob.o
obj-y += cpu.o
obj-y += cpu_dev.o
obj-y += e820.o
obj-y += mp.o
obj-y += mpio.o
obj-y += pci.o
obj-$(CONFIG_SYSINFO_SMBIOS) += smbios.o
obj-$(CONFIG_TURIN_REG_TRACE) += trace.o
obj-$(CONFIG_CMDLINE) += fch.o
obj-$(CONFIG_CMDLINE) += smn.o
obj-$(CONFIG_CMDLINE) += mca.o
